# BetterSit Configuration

# Язык сообщений (должен соответствовать файлу в папке languages, например en или ru)
language: en

# Центрировать ли игрока по центру блока при сидении?
center-on-block: true

# Смещение по высоте для сидения (отрицательное значение опускает)
sit-height-offset: -0.2
# Смещение по высоте для лежания (отрицательное значение опускает)
lay-height-offset: -0.8

# Задержка между использованиями /sit (в секундах). 0 - без задержки.
sit-cooldown: 0